### ISSUE TITLE
Вопрос ночи!

### ISSUE THREAD

**Issue by Ashura-Cyber** [anASStasi/TRPO#1]
Боба или Абоба?

**Comment by icnhndl** [comment]
Это достаточно сложный вопрос. Мне потребуется больше времени для ответа на этот вопрос. Отпишу позже.

**Comment by chelalina** [comment]
слишком сложный вопрос :(
но наверно я остановлюсь на варианте Боба

**Comment by Ashura-Cyber** [comment]
Я вас услышал, господа коллеги.
Тогда вопрос №2
Хлеб с маслом или масло с хлебом

**Comment by icnhndl** [comment]
Всё-таки боба

**Comment by icnhndl** [comment]
> Я вас услышал, господа коллеги. Тогда вопрос №2 Хлеб с маслом или масло с хлебом

масло с хлебом прикрепить на спину кота маслом  вверх. вечный двигАтель

**Comment by icnhndl** [comment]
ладно верну

**Comment by Ashura-Cyber** [comment]
Спасибо за ваши быстро принятые решения

**Comment by anASStasi** [comment]
аоаоаоааоао
