### ISSUE TITLE
Сюда быстро

### ISSUE THREAD

**Issue by icnhndl** [anASStasi/TRPO#2]

**Comment by icnhndl** [comment]
Здесь нужно понять нужно ли что-то понимать или можно понять что можно ничего не понимать и понять что можно закончить понимать и не понять

**Comment by anASStasi** [comment]
понимать или да или нет или зачем понимать да или да

**Comment by KISULZ** [comment]
Кто поменял название?

**Comment by KISULZ** [comment]
ВТФ У НАС ВООБЩЕ ЧТО-НИБУДЬ ГОТОВО?!
