### ISSUE TITLE
Каким будет наше название!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!111

### ISSUE THREAD

**Issue by anASStasi** [anASStasi/TRPO#3]

**Comment by anASStasi** [comment]
ДАВАЙТЕ СОЗДАДИМ МНОГО ОБСУЖДЕНИЙ будто мы решали много всегоооо

**Comment by anASStasi** [comment]
дайте ОБРАТНУЮ СВЯЗЬ!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by icnhndl** [comment]
ХЫЫХХЫХЫХЫХЫ

**Comment by Ashura-Cyber** [comment]
Мб создадим норм опрос
Чтобы его вставить в презентацию

**Comment by icnhndl** [comment]
не
зачем? тип  опрос в презентацию хз.  я могу по приколу оформить README.MD, вот это уже реально в презентацию добавить можно

**Comment by KISULZ** [comment]
Так наша игра будет называться ### **"Котарио"**

**Comment by KISULZ** [comment]
И это не ОБСУЖДАЕТСЯ!!!!
